### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by lowercasebtw** [CASELOAD7000/knockback-sync#16]
i mean you can use java, but may I ask why not use Kotlin?

**Comment by Axionize** [comment]
Lots of reasons, but the big one is the Minecraft ecosystem.

Java was chosen because it was the obvious and default choice. Kotlin has lots of amazing futures but doesn't have the developer base and support that choosing Java gives us access to. All the documentation is built for Java, the tooling is built for Java, and the developers in this space all use Java. There are other reasons, but this alone is a deal breaker.
 
As it stands right now, if you have some contributions in mind to make, we wouldn't be completely opposed if you made them in Kotlin so long as they were largely self-contained, although we would prefer changes be in Java for consistency.
